name: master-thesis
channels:
  - conda-forge
  - defaults
  - numba
dependencies:
  - coloredlogs
  - matplotlib
  - numpy
  - opencv
  - pandas
  - pip
  - pylint
  - python
  - scipy
  - spyder
  - tensorflow-gpu
  - keras-gpu
  - seaborn
  - scikit-learn
  - pillow
  - zlib
  - bzip2
  - progressbar2
  - pyyaml
  - h5py
  - trimesh
  - cudatoolkit
  - cudnn
  - pyculib
  - autopep8
  - pip:
    - pyrealsense2