name: master-thesis
channels:
  - defaults
  - numba
dependencies:
  - python
  - tensorflow-gpu=2.*
  - coloredlogs
  - matplotlib
  - opencv
  - pandas
  - pylint
  - pillow
  - zlib
  - bzip2
  - progressbar2
  - jupyter
  - scikit-learn
  - spyder
  - pyyaml
  - h5py
  - cudatoolkit=10.0.130
  - cudnn=7.6.4
  - autopep8
  - pip
  - lxml
  - tensorflow-probability
  - seaborn
  - pip:
    - pyrealsense2
    - pynput
    - pyttsx3
    - python-telegram-bot
    - googledrivedownloader