name: master-thesis
channels:
  - defaults
  - numba
dependencies:
  - python
  - tensorflow-gpu
  - keras-gpu
  - coloredlogs
  - matplotlib
  - opencv
  - pandas
  - pylint
  - pillow
  - zlib
  - bzip2
  - progressbar2
  - jupyter
  - spyder
  - pyyaml
  - h5py
  - cudatoolkit
  - cudnn
  - pyculib
  - autopep8
  - pip
  - pip:
    - pyrealsense2