name: master-thesis
channels:
  - conda-forge
  - defaults
dependencies:
  - coloredlogs
  - matplotlib
  - numpy
  - opencv
  - pandas
  - pip
  - pylint
  - python
  - scipy
  - spyder
  - tensorflow-gpu=1.14.0
  - keras-gpu=2.2.4
  - seaborn
  - scikit-learn=0.21.3
  - pillow
  - zlib
  - bzip2
  - progressbar2
  - pyyaml
  - h5py
  - trimesh
  - pip:
    - pyrealsense2
    - sklearn-compiledtrees
