name: master-thesis
channels:
  - conda-forge
  - defaults
dependencies:
  - coloredlogs
  - matplotlib
  - numpy
  - opencv
  - pandas
  - pip
  - python
  - scipy
  - spyder
  - tensorflow-gpu
  - pip:
    - pyrealsense2
